version: '3.9'

networks:
  default:

volumes:
  waku:
    name: 'waku-{{.Task.Slot}}'
  wakustore:
  redis:

services:
  redis:
    ports:
      - "6379:6379"
    image: 'redis:6-alpine'
    volumes:
      - redis:/data

  wakustore:
    image: ${WAKU_IMAGE}
    hostname: "wakustore"
    volumes:
      - wakustore:/mnt
    ports:
      - "8545:8545"
    command:
      - "wakunode"
      - "--nodekey=bbf358ab08ab29d70b6b20845e4aa417124bb8051ecdbaf4f822bba18f28f7fb"
      - "--persist-peers=true"
      - "--keep-alive=true"
      - "--swap=false"
      - "--rln-relay=false"
      - "--rpc=false"
      - "--relay=true"
      - "--store=true"
      - "--persist-messages=true"
      - "--filter=true"
      - "--db-path=/mnt"
      - "--topics=/waku/2/walletconnect/proto"

  waku:
    image: ${WAKU_IMAGE}
    hostname: "waku.{{.Task.Slot}}"
    volumes:
      - waku:/mnt
    environment:
      SWARM_PEERS: "tasks.{{.Service.Name}}"
      STORE_NODE_KEY: "16Uiu2HAkxthSUou6qdD5igzt6E4niDRbsXGTU6GpKNGKRahv6TTX"
    deploy:
      replicas: 3

  relay:
    image: ${RELAY_IMAGE}
    environment:
      REDIS_URL: "redis://redis:6379/0"
      WAKU_URL: "http://waku.{{.Task.Slot}}:8545"
    ports:
      - "5000:5000"
    deploy:
      replicas: 2

  externalrelay:
    image: ${RELAY_IMAGE}
    environment:
      REDIS_URL: "redis://redis:6379/0"
      WAKU_URL: "http://waku.3:8545"
    ports:
      - "5001:5000"
