name: Release

on:
  workflow_run:
    workflows: ["Tests"]
    types: [completed]
  push:
    tags: '*'

jobs:
  push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 0 is to get all git tags
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-stable
      - uses: cachix/cachix-action@v10
        with:
          name: walletconnect
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: make push-images
      - name: "Pushes nix store to cachix nix cache"
        run: make cachix
        env:
           CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
